name: "OpenTofu Deploy Website to Vercel"

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  tofu-deploy:
    env:
      VERCEL_API_TOKEN: ${{ secrets.VERCEL_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::434801484062:role/github-s3-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu format
        run: tofu fmt -check

      - name: OpenTofu Init
        run: tofu init

      - name: OpenTofu Validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        run: tofu plan -no-color

      - name: OpenTofu Apply
        run: tofu apply -no-color -auto-approve
